# Analyzing International Students Mental Health

![Illustration of silhouetted heads](mentalhealth.jpg)

Does going to university in a different country affect your mental health? A Japanese international university surveyed its students in 2018 and published a study the following year that was approved by several ethical and regulatory boards.

The study found that international students have a higher risk of mental health difficulties than the general population, and that social connectedness (belonging to a social group) and acculturative stress (stress associated with joining a new culture) are predictive of depression.

| Field Name    | Description                                      |
| ------------- | ------------------------------------------------ |
| `inter_dom`     | Types of students (international or domestic)   |
| `japanese_cate` | Japanese language proficiency                    |
| `english_cate`  | English language proficiency                     |
| `academic`      | Current academic level (undergraduate or graduate) |
| `age`           | Current age of student                           |
| `stay`          | Current length of stay in years                  |
| `todep`         | Total score of depression (PHQ-9 test)           |
| `tosc`          | Total score of social connectedness (SCS test)   |
| `toas`          | Total score of acculturative stress (ASISS test) |

In [8]:
-- View the data in students
SELECT * 
FROM students
LIMIT 5;

  inter_dom region  gender academic  ...  religion_bi  alone_bi  others_bi internet_bi
0     Inter    SEA    Male     Grad  ...           No        No         No          No
1     Inter    SEA    Male     Grad  ...           No        No         No          No
2     Inter    SEA    Male     Grad  ...           No        No         No          No
3     Inter     EA  Female     Grad  ...           No        No         No          No
4     Inter     EA  Female     Grad  ...          Yes        No         No          No

[5 rows x 50 columns]

The following variables will be analyzed:

| Field Name | Description |
| ---------- | ----------- |
| stay | Length of stay in years |
| count_int | Number of international students for each length of stay |
| average_phq | Average PHQ-9 test |
| average_scs | Average SCS test | 
| average_as | Average ASISS test |

In [9]:
-- Group by international student stays, in descending order 
SELECT 
	stay,
	COUNT(inter_dom) AS count_int,
	ROUND(AVG(todep), 2) AS average_phq,
	ROUND(AVG(tosc), 2) AS average_scs,
	ROUND(AVG(toas), 2) AS average_as
FROM students
WHERE inter_dom = 'Inter'
GROUP BY students.stay
ORDER BY stay DESC;

   stay  count_int  average_phq  average_scs  average_as
0    10          1        13.00        32.00       50.00
1     8          1        10.00        44.00       65.00
2     7          1         4.00        48.00       45.00
3     6          3         6.00        38.00       58.67
4     5          1         0.00        34.00       91.00
5     4         14         8.57        33.93       87.71
6     3         46         9.09        37.13       78.00
7     2         39         8.28        37.08       77.67
8     1         95         7.48        38.11       72.80

Being an international student usually means leaving everything behind to pursue a better career opportunity. Aside from the curriculums that require so much dedication, students see themselves facing many challenges that ultimately affect their academic performance due to stress, anxiety, and depression. International students that stayed 10 years had the highest average total score on the depression test (PHQ_9) but showed a lower average score of acculturative stress when compared to shorter stays. This could indicate their adaptiveness to the cultural norms of that state but still feel homesick, leading to higher rates of depression. New students only being a year or two into international living had high average acculturative stress scores, however, this peaked with students 7-8 years into international living.

   stay  count_int  average_phq  average_scs  average_as
0    10          1        13.00        32.00       50.00
1     8          1        10.00        44.00       65.00
2     7          1         4.00        48.00       45.00
3     6          3         6.00        38.00       58.67
4     5          1         0.00        34.00       91.00
5     4         14         8.57        33.93       87.71
6     3         46         9.09        37.13       78.00
7     2         39         8.28        37.08       77.67
8     1         95         7.48        38.11       72.80

As seen in the line graph above, there was a slight increase in depression in the first years, however it increased exponentially after the 5th year, reaching its peak at year 10.

   stay  count_int  average_phq  average_scs  average_as
0    10          1        13.00        32.00       50.00
1     8          1        10.00        44.00       65.00
2     7          1         4.00        48.00       45.00
3     6          3         6.00        38.00       58.67
4     5          1         0.00        34.00       91.00
5     4         14         8.57        33.93       87.71
6     3         46         9.09        37.13       78.00
7     2         39         8.28        37.08       77.67
8     1         95         7.48        38.11       72.80

In relation to social connectedness, the average scores are similar, but steadily increased after year 5. The average score for social connectedness peaked at the 7th year with an average score of 48.

   stay  count_int  average_phq  average_scs  average_as
0    10          1        13.00        32.00       50.00
1     8          1        10.00        44.00       65.00
2     7          1         4.00        48.00       45.00
3     6          3         6.00        38.00       58.67
4     5          1         0.00        34.00       91.00
5     4         14         8.57        33.93       87.71
6     3         46         9.09        37.13       78.00
7     2         39         8.28        37.08       77.67
8     1         95         7.48        38.11       72.80

Acculturative stress was present significantly at year 5 and decreased right after, reaching its lowest average score in the 7th year.

In [13]:
-- 
SELECT
	english_cate,
	ROUND(AVG(stay), 2) AS average_stay,
	ROUND(AVG(todep), 2) AS average_phq,
	ROUND(AVG(tosc), 2) AS average_scs,
	ROUND(AVG(toas), 2) AS average_as
FROM students
WHERE inter_dom = 'Inter'
GROUP BY students.english_cate
ORDER BY average_stay DESC

  english_cate  average_stay  average_phq  average_scs  average_as
0         High          2.16         7.93        37.42       75.50
1      Average          1.76         8.46        36.93       75.66
2          Low          1.71         8.00        40.29       76.43

  english_cate  average_stay  average_phq  average_scs  average_as
0         High          2.16         7.93        37.42       75.50
1      Average          1.76         8.46        36.93       75.66
2          Low          1.71         8.00        40.29       76.43

Students that have stayed for more than two years had a higher english proficiency rate and also showed lower average rates of depression on the PHQ-9 test.

Overall, international student go through multiple hurrdles in pursuit of higher education. Aside from the curriculum, their mental health takes a toll due to being away from everything they've known. The pressure of fitting in, making sure they pass their courses, and have a social life contributes to the levels of depression, social connectedness, and acculturative stress shown here.